{{- range .Values.services.redis.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    app: {{ .name }}
spec:
  type: {{ .serviceType }}
  ports:
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .targetPort }}
  selector:
    app: redis
---
{{- end }}
